#!/usr/bin/env python3
"""check_findings.py — Validate FINDINGS.md claims against output artifacts.

Auto-generated by gen_findings_audit.py from project.yaml.
Re-run generator after changing project.yaml audit configuration.

Project: Experiment

This script:
  1. Reads FINDINGS.md and extracts all claim tags, evidence paths, numeric values,
     hypothesis references, and figure references.
  2. Validates that every [DEMONSTRATED] claim has an evidence artifact that exists.
  3. Cross-references numeric values against output JSON/CSV data.
  4. Verifies hypothesis references (H-X) exist in HYPOTHESIS_REGISTRY.md.
  5. Checks that referenced figures exist in figures/ or blog/images/.
  6. Scans for prohibited language in [DEMONSTRATED] claims.
  7. Reports claim tag coverage percentage.

Exit codes:
  0 — All checks passed
  1 — One or more CRITICAL checks failed
"""
import argparse
import csv
import json
import os
import re
import sys
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Configuration (derived from project.yaml at generation time)
# ---------------------------------------------------------------------------

DEFAULT_FINDINGS_PATH = "FINDINGS.md"
DEFAULT_OUTPUTS_DIR = "outputs"
DEFAULT_HYPOTHESIS_REGISTRY = "HYPOTHESIS_REGISTRY.md"
FIGURE_DIRS = ["figures", "blog/images", "outputs/figures"]
PROHIBITED_LANGUAGE = ["novel", "first", "validates", "proves", "breakthrough"]
VALID_CLAIM_TAGS = ["DEMONSTRATED", "SUGGESTED", "PROJECTED", "HYPOTHESIZED"]
MIN_SEEDS = 3


# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------

# Matches claim tags like [DEMONSTRATED], [SUGGESTED, SYNTHETIC], etc.
_CLAIM_TAG_RE = re.compile(
    r"\[("
    + "|".join(VALID_CLAIM_TAGS)
    + r")(?:,\s*[A-Z_-]+)*\]"
)

# Matches hypothesis references like H-1, H-2, H-12
_HYPOTHESIS_REF_RE = re.compile(r"\bH-(\d+)\b")

# Matches evidence artifact paths (files referenced in backticks or after "Evidence:" etc.)
_EVIDENCE_PATH_RE = re.compile(
    r"`([^`]+\.(?:json|csv|txt|png|pdf|svg|jpg|jpeg|npz|pkl))`"
)

# Matches figure references like Figure 1, Fig. 2, F1, etc.
_FIGURE_REF_RE = re.compile(
    r"(?:Figure|Fig\.?)\s*(\d+)"
    r"|\bF(\d+)\b"
)

# Matches image paths in markdown: ![...](path)
_IMAGE_PATH_RE = re.compile(
    r"!\[[^\]]*\]\(([^)]+)\)"
)

# Matches numeric values (with optional sign, commas, decimals, percent)
_NUMBER_RE = re.compile(
    r"(?<![\w\\])"
    r"([+-])?"
    r"(\d{1,3}"
    r"(?:,\d{3})*"
    r"(?:\.\d+)?)"
    r"(%?)"
    r"(?![\w])"
)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

class Finding:
    """A single audit finding."""

    def __init__(self, check: str, severity: str, message: str, line: int = 0):
        self.check = check
        self.severity = severity
        self.message = message
        self.line = line

    def __repr__(self) -> str:
        loc = f" (line {self.line})" if self.line else ""
        return f"[{self.severity}] {self.check}{loc}: {self.message}"


# ---------------------------------------------------------------------------
# FINDINGS.md parsing
# ---------------------------------------------------------------------------

def parse_findings(findings_path: Path) -> dict:
    """Parse FINDINGS.md and extract structured data.

    Returns a dict with:
      text: full text
      lines: list of (line_num, line_text) tuples
      claims: list of dicts with tag, line_num, line_text, qualifiers
      evidence_paths: list of (path_str, line_num) tuples
      hypothesis_refs: list of (h_id, line_num) tuples
      figure_refs: list of (fig_num, line_num) tuples
      image_paths: list of (path_str, line_num) tuples
      numbers: list of dicts with value, raw, is_pct, line_num, context
    """
    text = findings_path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()

    claims = []
    evidence_paths = []
    hypothesis_refs = []
    figure_refs = []
    image_paths = []
    numbers = []

    for i, line in enumerate(lines, start=1):
        # Extract claim tags
        for m in _CLAIM_TAG_RE.finditer(line):
            tag_text = m.group(0)
            base_tag = m.group(1)
            # Extract qualifiers
            qualifiers = [q.strip() for q in tag_text[1:-1].split(",")]
            claims.append({
                "tag": base_tag,
                "qualifiers": qualifiers,
                "line_num": i,
                "line_text": line.strip(),
                "full_tag": tag_text,
            })

        # Extract evidence paths
        for m in _EVIDENCE_PATH_RE.finditer(line):
            evidence_paths.append((m.group(1), i))

        # Extract hypothesis references
        for m in _HYPOTHESIS_REF_RE.finditer(line):
            hypothesis_refs.append((int(m.group(1)), i))

        # Extract figure references
        for m in _FIGURE_REF_RE.finditer(line):
            fig_num = m.group(1) or m.group(2)
            if fig_num:
                figure_refs.append((int(fig_num), i))

        # Extract image paths
        for m in _IMAGE_PATH_RE.finditer(line):
            image_paths.append((m.group(1), i))

        # Extract numeric values (skip headers, metadata, legends)
        stripped = line.strip()
        if stripped.startswith("#") or stripped.startswith("|") or stripped.startswith(">"):
            continue
        if stripped.startswith("**Data type") or stripped.startswith("**Seeds"):
            continue

        for m in _NUMBER_RE.finditer(line):
            raw = m.group(0)
            val_str = m.group(2).replace(",", "")
            try:
                val = float(val_str)
            except ValueError:
                continue
            if m.group(1) == "-":
                val = -val
            # Skip trivially small integers and years
            if val in (0, 1, 2, 3) and not m.group(3):
                continue
            if 1900 <= val <= 2100 and not m.group(3):
                continue

            # Build context
            idx = m.start()
            ctx_start = max(0, idx - 60)
            ctx_end = min(len(line), idx + len(raw) + 60)
            context = line[ctx_start:ctx_end].strip()

            numbers.append({
                "value": val,
                "raw": raw,
                "is_pct": m.group(3) == "%",
                "line_num": i,
                "context": context,
            })

    return {
        "text": text,
        "lines": [(i, l) for i, l in enumerate(lines, start=1)],
        "claims": claims,
        "evidence_paths": evidence_paths,
        "hypothesis_refs": hypothesis_refs,
        "figure_refs": figure_refs,
        "image_paths": image_paths,
        "numbers": numbers,
    }


# ---------------------------------------------------------------------------
# Check 1: Evidence artifact existence
# ---------------------------------------------------------------------------

def check_evidence_artifacts(
    claims: list[dict],
    evidence_paths: list[tuple[str, int]],
    project_dir: Path,
    outputs_dir: Path,
) -> list[Finding]:
    """Verify that every [DEMONSTRATED] claim has an evidence artifact that exists."""
    findings: list[Finding] = []

    # Collect all demonstrated claim line numbers
    demonstrated_lines = set()
    for c in claims:
        if c["tag"] == "DEMONSTRATED":
            demonstrated_lines.add(c["line_num"])

    # Check all evidence paths exist
    missing_artifacts = []
    found_artifacts = []
    for path_str, line_num in evidence_paths:
        # Try multiple resolution strategies
        candidates = [
            project_dir / path_str,
            outputs_dir / path_str,
            project_dir / "outputs" / path_str,
        ]
        found = False
        for candidate in candidates:
            if candidate.exists():
                found = True
                found_artifacts.append((path_str, line_num))
                break
        if not found:
            missing_artifacts.append((path_str, line_num))
            findings.append(Finding(
                "evidence_artifact", "CRITICAL",
                f"Evidence artifact not found: {path_str}",
                line=line_num,
            ))

    # Check that demonstrated claims near evidence paths have valid artifacts
    # (within 5 lines of the claim)
    for c in claims:
        if c["tag"] != "DEMONSTRATED":
            continue
        nearby_evidence = [
            p for p, ln in evidence_paths
            if abs(ln - c["line_num"]) <= 5
        ]
        if not nearby_evidence:
            findings.append(Finding(
                "evidence_artifact", "WARNING",
                f"[DEMONSTRATED] claim has no nearby evidence path reference",
                line=c["line_num"],
            ))

    if not missing_artifacts and demonstrated_lines:
        findings.append(Finding(
            "evidence_artifact", "PASS",
            f"All {len(found_artifacts)} evidence artifact paths resolve to existing files",
        ))
    elif not evidence_paths:
        findings.append(Finding(
            "evidence_artifact", "WARNING",
            "No evidence artifact paths found in FINDINGS.md",
        ))

    return findings


# ---------------------------------------------------------------------------
# Check 2: Numeric value cross-reference
# ---------------------------------------------------------------------------

def load_all_data(outputs_dir: Path) -> dict[str, Any]:
    """Load all numeric data from JSON and CSV files in outputs/."""
    data: dict[str, Any] = {}

    if not outputs_dir.exists():
        return data

    for fpath in sorted(outputs_dir.rglob("*")):
        if not fpath.is_file():
            continue

        rel = str(fpath.relative_to(outputs_dir))
        suffix = fpath.suffix.lower()

        if suffix == ".json":
            try:
                raw = json.loads(fpath.read_text(encoding="utf-8"))
                _flatten_json(raw, rel.rsplit(".", 1)[0], data)
            except Exception:
                pass
        elif suffix == ".csv":
            try:
                with open(fpath, newline="", encoding="utf-8") as f:
                    reader = csv.DictReader(f)
                    for row_idx, row in enumerate(reader):
                        for col, val in row.items():
                            if col is None:
                                continue
                            try:
                                num = float(val.replace(",", ""))
                                key = f"{rel.rsplit('.', 1)[0]}.{col}"
                                data.setdefault(key, []).append(num)
                            except (ValueError, AttributeError):
                                pass
            except Exception:
                pass

    return data


def _flatten_json(obj: Any, prefix: str, out: dict[str, Any]) -> None:
    """Recursively flatten JSON into dotted-key -> value pairs."""
    if isinstance(obj, dict):
        for k, v in obj.items():
            key = f"{prefix}.{k}" if prefix else k
            _flatten_json(v, key, out)
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            _flatten_json(v, f"{prefix}[{i}]", out)
    elif isinstance(obj, (int, float)) and not isinstance(obj, bool):
        out[prefix] = float(obj)


def check_numeric_values(
    numbers: list[dict],
    outputs_dir: Path,
    tolerance: float = 0.01,
) -> list[Finding]:
    """Cross-reference numeric values in FINDINGS.md against output data."""
    findings: list[Finding] = []

    all_data = load_all_data(outputs_dir)
    if not all_data:
        findings.append(Finding(
            "numeric_crossref", "WARNING",
            f"No numeric data found in {outputs_dir} — cannot cross-reference",
        ))
        return findings

    # Collect all unique numeric values from data
    data_values: set[float] = set()
    for v in all_data.values():
        if isinstance(v, list):
            data_values.update(v)
        elif isinstance(v, (int, float)):
            data_values.add(float(v))

    matched = 0
    unmatched = 0

    for entry in numbers:
        val = entry["value"]
        # Check percentage: if is_pct, also check val/100
        candidates = [val]
        if entry["is_pct"]:
            candidates.append(val / 100.0)

        found = False
        for candidate in candidates:
            for dv in data_values:
                if dv == 0 and candidate == 0:
                    found = True
                    break
                if dv == 0:
                    continue
                rel_diff = abs(candidate - dv) / max(abs(dv), 1e-12)
                abs_diff = abs(candidate - dv)
                if abs_diff <= tolerance or rel_diff <= tolerance:
                    found = True
                    break
            if found:
                break

        if found:
            matched += 1
        else:
            unmatched += 1
            # Only flag if the number looks like a metric (has decimal or %)
            if "." in entry["raw"] or entry["is_pct"]:
                findings.append(Finding(
                    "numeric_crossref", "WARNING",
                    f"Numeric value {entry['raw']} not found in output data",
                    line=entry["line_num"],
                ))

    total = matched + unmatched
    if total > 0:
        pct = matched / total * 100
        sev = "PASS" if pct >= 80 else "WARNING"
        findings.append(Finding(
            "numeric_crossref", sev,
            f"{matched}/{total} numeric values ({pct:.0f}%) matched in output data",
        ))

    return findings


# ---------------------------------------------------------------------------
# Check 3: Hypothesis references
# ---------------------------------------------------------------------------

def check_hypothesis_refs(
    hypothesis_refs: list[tuple[int, int]],
    project_dir: Path,
    registry_path: str,
) -> list[Finding]:
    """Verify that every H-X reference exists in HYPOTHESIS_REGISTRY.md."""
    findings: list[Finding] = []

    reg_path = project_dir / registry_path
    if not reg_path.exists():
        # Also check common locations
        for alt in [project_dir / "HYPOTHESIS_REGISTRY.md", project_dir / "docs" / registry_path]:
            if alt.exists():
                reg_path = alt
                break

    if not reg_path.exists():
        if hypothesis_refs:
            findings.append(Finding(
                "hypothesis_refs", "CRITICAL",
                f"HYPOTHESIS_REGISTRY.md not found at {registry_path} but "
                f"{len(hypothesis_refs)} hypothesis references found in FINDINGS.md",
            ))
        else:
            findings.append(Finding(
                "hypothesis_refs", "PASS",
                "No hypothesis references and no registry file — OK",
            ))
        return findings

    # Parse registry for defined hypothesis IDs
    reg_text = reg_path.read_text(encoding="utf-8", errors="replace")
    defined_ids = set()
    for m in re.finditer(r"\bH-(\d+)\b", reg_text):
        defined_ids.add(int(m.group(1)))

    # Check each reference
    missing = []
    for h_id, line_num in hypothesis_refs:
        if h_id not in defined_ids:
            missing.append((h_id, line_num))
            findings.append(Finding(
                "hypothesis_refs", "CRITICAL",
                f"Hypothesis H-{h_id} referenced but not defined in registry",
                line=line_num,
            ))

    if not missing and hypothesis_refs:
        findings.append(Finding(
            "hypothesis_refs", "PASS",
            f"All {len(hypothesis_refs)} hypothesis references resolve to registry entries",
        ))
    elif not hypothesis_refs:
        findings.append(Finding(
            "hypothesis_refs", "WARNING",
            "No hypothesis references found in FINDINGS.md",
        ))

    return findings


# ---------------------------------------------------------------------------
# Check 4: Figure existence
# ---------------------------------------------------------------------------

def check_figure_existence(
    figure_refs: list[tuple[int, int]],
    image_paths: list[tuple[str, int]],
    project_dir: Path,
) -> list[Finding]:
    """Verify that every referenced figure exists in figures/ or blog/images/."""
    findings: list[Finding] = []

    # Check explicit image paths
    missing_images = []
    for img_path, line_num in image_paths:
        candidates = [project_dir / img_path]
        for fig_dir in FIGURE_DIRS:
            candidates.append(project_dir / fig_dir / Path(img_path).name)
        found = any(c.exists() for c in candidates)
        if not found:
            missing_images.append((img_path, line_num))
            findings.append(Finding(
                "figure_existence", "CRITICAL",
                f"Referenced image not found: {img_path}",
                line=line_num,
            ))

    # Check numbered figure references against files in figure directories
    available_figures: set[int] = set()
    for fig_dir_name in FIGURE_DIRS:
        fig_dir = project_dir / fig_dir_name
        if fig_dir.exists():
            for f in fig_dir.iterdir():
                if f.is_file():
                    # Try to extract figure number from filename (e.g., f1_xxx.png)
                    m = re.match(r"f(\d+)[_.]", f.name, re.IGNORECASE)
                    if m:
                        available_figures.add(int(m.group(1)))

    missing_numbered = []
    for fig_num, line_num in figure_refs:
        if available_figures and fig_num not in available_figures:
            missing_numbered.append((fig_num, line_num))
            findings.append(Finding(
                "figure_existence", "WARNING",
                f"Figure {fig_num} referenced but no matching file found (f{fig_num}_*)",
                line=line_num,
            ))

    total_refs = len(image_paths) + len(figure_refs)
    total_missing = len(missing_images) + len(missing_numbered)

    if total_refs > 0 and total_missing == 0:
        findings.append(Finding(
            "figure_existence", "PASS",
            f"All {total_refs} figure/image references resolved",
        ))
    elif total_refs == 0:
        findings.append(Finding(
            "figure_existence", "WARNING",
            "No figure or image references found in FINDINGS.md",
        ))

    return findings


# ---------------------------------------------------------------------------
# Check 5: Prohibited language in [DEMONSTRATED] claims
# ---------------------------------------------------------------------------

def check_prohibited_language(
    claims: list[dict],
    lines: list[tuple[int, str]],
) -> list[Finding]:
    """Scan for prohibited language near [DEMONSTRATED] claims."""
    findings: list[Finding] = []

    # Build a set of line numbers with DEMONSTRATED claims
    demonstrated_lines = {c["line_num"] for c in claims if c["tag"] == "DEMONSTRATED"}

    violations = []
    for line_num, line_text in lines:
        # Check lines with DEMONSTRATED claims (and 2 lines before/after for context)
        near_demonstrated = any(
            abs(line_num - dl) <= 2 for dl in demonstrated_lines
        )
        if not near_demonstrated:
            continue

        line_lower = line_text.lower()
        for word in PROHIBITED_LANGUAGE:
            # Word boundary match
            pattern = r"\b" + re.escape(word) + r"\b"
            if re.search(pattern, line_lower):
                # Exclude if the word is in a quote or citation
                if line_text.strip().startswith(">") or line_text.strip().startswith('"'):
                    continue
                violations.append((word, line_num, line_text.strip()[:100]))
                findings.append(Finding(
                    "prohibited_language", "CRITICAL",
                    f"Prohibited word '{word}' near [DEMONSTRATED] claim",
                    line=line_num,
                ))

    if not violations:
        findings.append(Finding(
            "prohibited_language", "PASS",
            f"No prohibited language found near {len(demonstrated_lines)} [DEMONSTRATED] claims",
        ))

    return findings


# ---------------------------------------------------------------------------
# Check 6: Claim tag coverage
# ---------------------------------------------------------------------------

def check_claim_coverage(
    claims: list[dict],
    numbers: list[dict],
    text: str,
) -> list[Finding]:
    """Check that claim tag coverage is 100% of quantitative findings."""
    findings: list[Finding] = []

    # Count lines that contain quantitative claims (numbers in non-header lines)
    quantitative_lines = set()
    for entry in numbers:
        quantitative_lines.add(entry["line_num"])

    # Count lines that have claim tags
    tagged_lines = set()
    for c in claims:
        tagged_lines.add(c["line_num"])

    total_claims = len(claims)

    if total_claims == 0:
        findings.append(Finding(
            "claim_coverage", "WARNING",
            "No claim tags found in FINDINGS.md — expected 100% coverage",
        ))
        return findings

    # Count claims by tag
    tag_counts: dict[str, int] = {}
    for c in claims:
        tag_counts[c["tag"]] = tag_counts.get(c["tag"], 0) + 1

    # Calculate coverage: tagged quantitative lines / total quantitative lines
    tagged_quant = quantitative_lines & tagged_lines
    if quantitative_lines:
        coverage = len(tagged_quant) / len(quantitative_lines) * 100
    else:
        coverage = 100.0  # no quantitative lines = vacuous pass

    sev = "PASS" if coverage >= 90 else ("WARNING" if coverage >= 50 else "CRITICAL")
    tag_summary = ", ".join(f"{t}={n}" for t, n in sorted(tag_counts.items()))
    findings.append(Finding(
        "claim_coverage", sev,
        f"Claim tag coverage: {coverage:.0f}% ({len(tagged_quant)}/{len(quantitative_lines)} "
        f"quantitative lines tagged). Tags: {tag_summary}. Total claims: {total_claims}.",
    ))

    return findings


# ---------------------------------------------------------------------------
# Check 7: Required research quality sections (Novelty, Impact, Generalization)
# ---------------------------------------------------------------------------

def check_required_sections(text: str) -> list[Finding]:
    """Verify that research quality dimension sections exist in FINDINGS.md."""
    findings: list[Finding] = []

    required_sections = {
        "Novelty Assessment": "Describes how findings advance beyond prior work",
        "Practitioner Impact": "Explains practical applications and artifacts released",
        "Generalization Analysis": "Discusses scope, transferability, and boundary conditions",
    }
    optional_sections = {
        "Cross-Domain Connections": "Describes connections to other domains (optional for single-domain)",
    }

    for section_name, description in required_sections.items():
        pattern = re.compile(r"^##\s+" + re.escape(section_name), re.MULTILINE | re.IGNORECASE)
        if pattern.search(text):
            findings.append(Finding(
                "required_sections", "PASS",
                f"Required section present: {section_name}",
            ))
        else:
            findings.append(Finding(
                "required_sections", "WARNING",
                f"Missing section: {section_name} — {description}",
            ))

    for section_name, description in optional_sections.items():
        pattern = re.compile(r"^##\s+" + re.escape(section_name), re.MULTILINE | re.IGNORECASE)
        if pattern.search(text):
            findings.append(Finding(
                "required_sections", "PASS",
                f"Optional section present: {section_name}",
            ))
        # No warning for optional sections

    return findings


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def run_all_checks(
    findings_path: Path,
    project_dir: Path,
    outputs_dir: Path,
    registry_path: str,
) -> list[Finding]:
    """Run all findings audit checks."""
    all_findings: list[Finding] = []

    # Parse FINDINGS.md
    if not findings_path.exists():
        all_findings.append(Finding(
            "parse", "CRITICAL",
            f"FINDINGS.md not found at {findings_path}",
        ))
        return all_findings

    parsed = parse_findings(findings_path)
    print(f"  Parsed FINDINGS.md:")
    print(f"    Claims:      {len(parsed['claims'])}")
    print(f"    Evidence:    {len(parsed['evidence_paths'])}")
    print(f"    Hypotheses:  {len(parsed['hypothesis_refs'])}")
    print(f"    Figures:     {len(parsed['figure_refs'])}")
    print(f"    Images:      {len(parsed['image_paths'])}")
    print(f"    Numbers:     {len(parsed['numbers'])}")
    print()

    # Check 1: Evidence artifact existence
    print("  Check 1: Evidence artifact existence...")
    all_findings.extend(check_evidence_artifacts(
        parsed["claims"], parsed["evidence_paths"],
        project_dir, outputs_dir,
    ))

    # Check 2: Numeric value cross-reference
    print("  Check 2: Numeric value cross-reference...")
    all_findings.extend(check_numeric_values(
        parsed["numbers"], outputs_dir,
    ))

    # Check 3: Hypothesis references
    print("  Check 3: Hypothesis references...")
    all_findings.extend(check_hypothesis_refs(
        parsed["hypothesis_refs"], project_dir, registry_path,
    ))

    # Check 4: Figure existence
    print("  Check 4: Figure existence...")
    all_findings.extend(check_figure_existence(
        parsed["figure_refs"], parsed["image_paths"], project_dir,
    ))

    # Check 5: Prohibited language
    print("  Check 5: Prohibited language scan...")
    all_findings.extend(check_prohibited_language(
        parsed["claims"], parsed["lines"],
    ))

    # Check 6: Claim tag coverage
    print("  Check 6: Claim tag coverage...")
    all_findings.extend(check_claim_coverage(
        parsed["claims"], parsed["numbers"], parsed["text"],
    ))

    # Check 7: Required research quality sections
    print("  Check 7: Required research quality sections...")
    all_findings.extend(check_required_sections(
        parsed["text"],
    ))

    return all_findings


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def print_summary(findings: list[Finding]) -> None:
    """Print human-readable summary."""
    critical = [f for f in findings if f.severity == "CRITICAL"]
    warnings = [f for f in findings if f.severity == "WARNING"]
    passes = [f for f in findings if f.severity == "PASS"]

    print()
    print("=" * 70)
    print("FINDINGS AUDIT RESULTS")
    print("=" * 70)
    print(f"  CRITICAL: {len(critical)}")
    print(f"  WARNING:  {len(warnings)}")
    print(f"  PASS:     {len(passes)}")
    print("-" * 70)

    if critical:
        print()
        print("CRITICAL FAILURES:")
        for f in critical:
            loc = f" (line {f.line})" if f.line else ""
            print(f"  [CRITICAL] [{f.check}]{loc}: {f.message}")
        print()

    if warnings:
        print("WARNINGS:")
        for f in warnings:
            loc = f" (line {f.line})" if f.line else ""
            print(f"  [WARNING] [{f.check}]{loc}: {f.message}")
        print()

    # Per-check verdict table
    print("PER-CHECK VERDICTS:")
    checks_seen = []
    for f in findings:
        if f.check not in checks_seen:
            checks_seen.append(f.check)

    for check_name in checks_seen:
        check_findings = [f for f in findings if f.check == check_name]
        has_critical = any(f.severity == "CRITICAL" for f in check_findings)
        has_warning = any(f.severity == "WARNING" for f in check_findings)
        if has_critical:
            verdict = "FAIL (CRITICAL)"
        elif has_warning:
            verdict = "WARN"
        else:
            verdict = "PASS"
        print(f"  {check_name:<25} {verdict}")

    print()
    if critical:
        print(f"  RESULT: FAIL ({len(critical)} critical issues)")
    else:
        print("  RESULT: PASS")
    print("=" * 70)


def write_findings_json(findings: list[Finding], output_path: Path) -> None:
    """Write findings to JSON."""
    report = {
        "summary": {
            "total": len(findings),
            "critical": sum(1 for f in findings if f.severity == "CRITICAL"),
            "warning": sum(1 for f in findings if f.severity == "WARNING"),
            "pass": sum(1 for f in findings if f.severity == "PASS"),
        },
        "findings": [
            {
                "check": f.check,
                "severity": f.severity,
                "message": f.message,
                "line": f.line,
            }
            for f in findings
        ],
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2) + "\n")
    print(f"  JSON findings written: {output_path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Validate FINDINGS.md claims against output artifacts, "
                    "hypothesis registry, and claim strength rules.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python check_findings.py --project-dir .
    python check_findings.py --project-dir . --findings FINDINGS.md --outputs outputs/
    python check_findings.py --project-dir . --json findings_audit.json
        """,
    )
    parser.add_argument(
        "--project-dir", default=".",
        help="Project root directory (default: .)",
    )
    parser.add_argument(
        "--findings", default=DEFAULT_FINDINGS_PATH,
        help=f"Path to FINDINGS.md (default: {DEFAULT_FINDINGS_PATH})",
    )
    parser.add_argument(
        "--outputs", default=DEFAULT_OUTPUTS_DIR,
        help=f"Path to outputs directory (default: {DEFAULT_OUTPUTS_DIR})",
    )
    parser.add_argument(
        "--registry", default=DEFAULT_HYPOTHESIS_REGISTRY,
        help=f"Path to HYPOTHESIS_REGISTRY.md (default: {DEFAULT_HYPOTHESIS_REGISTRY})",
    )
    parser.add_argument(
        "--json", default=None,
        help="Output path for JSON findings report (optional)",
    )

    args = parser.parse_args()

    project_dir = Path(args.project_dir).resolve()
    findings_path = project_dir / args.findings
    outputs_dir = project_dir / args.outputs

    print(f"Findings Audit — {project_dir.name}")
    print(f"  FINDINGS.md: {findings_path}")
    print(f"  Outputs:     {outputs_dir}")
    print(f"  Registry:    {args.registry}")
    print()

    # Run checks
    all_findings = run_all_checks(
        findings_path, project_dir, outputs_dir, args.registry,
    )

    # Output
    if args.json:
        write_findings_json(all_findings, Path(args.json))

    print_summary(all_findings)

    # Exit code
    has_critical = any(f.severity == "CRITICAL" for f in all_findings)
    sys.exit(1 if has_critical else 0)


if __name__ == "__main__":
    main()
